### ISSUE TITLE
Pusher does not work inside of aws lambda

### ISSUE THREAD

**Issue by sashank007** [pusher/pusher-http-node#112]
My pusher code works fine locally but does not work in AWS lambda. Is there any configuration I am missing inside of AWS or pusher? I am using a public channel.

**Comment by gurusoft13** [comment]
Have you tried with another Pusher credential?

When we create the Pusher account, we can set the cluster ap1(Asia Pacific 1) ap2, ..., EU(European), us1, us2, u3.
So we need to choose the corresponding regional cluster for your server in which your wanna use the pusher.
So try to change the cluster for your current Pusher app or create new Pusher app.
Hope it will work
