### ISSUE TITLE
Subscribing to channels.

### ISSUE THREAD

**Issue by AlexanderGipp** [pusher/pusher-http-node#148]
How do i subscribe to a channel?

like:
```js
var channel = pusher.subscribe(channelName);
```

**Comment by benw-pusher** [comment]
It is not possible to subscribe to a channel using this pusher-http-node library. 
Our http libraries, such as this library, are intended for interacting with our http API and authenticating subscriptions. 

Our client libraries, such as our [pusher-js ](https://github.com/pusher/pusher-js)library, can subscribe to channels and consume events. 

You can read more about our libraries and their functions [in our documentation](https://pusher.com/docs/channels/channels_libraries/libraries/).
