### ISSUE TITLE
Add types/node-fetch to dependencies rather than devDependencies

### ISSUE THREAD

**Issue by fspoettel** [pusher/pusher-http-node#150]
Using this library in a typescript project causes the following error on compile:

```
Could not find a declaration file for module 'node-fetch'. '/app/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
```

This is caused by `@types/node-fetch` being a `devDependency` rather than a `dependency` and thus not being installed when consuming it as an npm package. Installing this `@types/node-fetch` module manually resolves the issue but is a messy workaround.

The Typescript handbook [advises to add dependent `@types` to dependencies](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies) to mitigate this problem. It is also commonly done in other typescript libs that do not bundle their output, see e.g. [got](https://github.com/sindresorhus/got/blob/main/package.json#L49-L50).

**Comment by amad** [comment]
I'm not sure if this suggestion will lead to version conflict for some other users that use `@types/node-fetch` or not. If it doesn't, then it's a good suggestion.
Another alternative is to not export any type from `node-fetch`. Then we can keep it a `devDependency`.

**Comment by fspoettel** [comment]
this shouldn't be a problem from a pure module resolution standpoint. both `npm` and `yarn`  try to hoist modules to the root `node_modules` folder in a best effort manner.

If that is not possible due to multiple versions of a package being required - for instance _package-a_ requires `uuid^3.0` and _package-b_ requires `uuid^4.0`, then these versions would be moved to a `node_modules` folder in the individual packages. This works because the `node` module resolution process looks for packages in a bottom-up manner.

I found an [old npm blog post](https://npm.github.io/how-npm-works-docs/npm3/how-npm3-works.html) that has details. I gave it a quick test with the module in question and it works as described.

**Comment by omondibrian** [comment]
> Using this library in a typescript project causes the following error on compile:
> 
> ```
> Could not find a declaration file for module 'node-fetch'. '/app/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
> ```
> 
> This is caused by `@types/node-fetch` being a `devDependency` rather than a `dependency` and thus not being installed when consuming it as an npm package. Installing this `@types/node-fetch` module manually resolves the issue but is a messy workaround.
> 
> The Typescript handbook [advises to add dependent `@types` to dependencies](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies) to mitigate this problem. It is also commonly done in other typescript libs that do not bundle their output, see e.g. [got](https://github.com/sindresorhus/got/blob/main/package.json#L49-L50).

do you install it in your main package.json or pusher

**Comment by fspoettel** [comment]
The manual workaround for consumers is to install `@types/node-fetch` in the package.json where `pusher-http-node` is a dependency, which is your main package.json in most cases.

**Comment by JonahTurnquist** [comment]
This is also causing me headaches - the workaround didn't work for me either

**Comment by isaachinman** [comment]
This issue is still valid, and is a very easy fix.

**Comment by jlcarvalho** [comment]
This issue is still happening.

**Comment by isaachinman** [comment]
@sonologico Can we get a response here? Especially with Node v18, which has built-in fetch, the `node-fetch` dependency needs to be fixed.

**Comment by sonologico** [comment]
`@types/node-fetch` moved into `dependencies` in 5.1.2. Thanks for reporting this.
