### ISSUE TITLE
Request: debug logging 

### ISSUE THREAD

**Issue by joeyfigaro** [pusher/pusher-http-node#159]
Currently pusher on the server is very much a blackbox–awaiting `trigger` spins indefinitely with no information in the dashboard or in console. It'd be awesome if we could enable logging to console just like the client library.

**Comment by joeyfigaro** [comment]
Example of what encountering errors looks like currently:

```
Error:
    at new RequestError (/xxx/packages/common/node_modules/pusher/lib/errors.js:13:16)
    at /xxx/packages/common/node_modules/pusher/lib/requests.js:74:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[ERROR] 15:59:03 PusherRequestError: Request failed with an error
```

Not a whole lot to go off of here. 😢

**Comment by benw-pusher** [comment]
You should be able to catch the error and then extract the error code/message. See https://github.com/pusher/pusher-http-node/blob/e74721a6eeb331c5c4f86f9b90e90a2a67e89867/lib/errors.js#L11 for info on what properties of the Error should be available.
