### ISSUE TITLE
pusher causing uncaughtExceptions

### ISSUE THREAD

**Issue by bosticka** [pusher/pusher-http-node#161]
From time to time I get these (sanitized) on my nodejs server (it's intermittent):

{}
node:internal/process/promises:279
 triggerUncaughtException(err, true /* fromPromise */);
 ^
Error
 at new RequestError (/home/build/.../server/node_modules/pusher/lib/errors.js:13:16)
 at /home/build/.../server/node_modules/pusher/lib/requests.js:74:13
 at runMicrotasks (<anonymous>)
 at processTicksAndRejections (node:internal/process/task_queues:96:5) {
 name: 'PusherRequestError',
 message: 'Request failed with an error',
 url: 'https://api-us2.pusher.com/apps/357507/events?auth_key=...&auth_timestamp=1649968615&auth_version=1.0&body_md5=...auth_signature=...,
 error: FetchError: request to https://api-us2.pusher.com/apps/357507/events?auth_key=...&auth_timestamp=1649968615&auth_version=1.0&body_md5=...&auth_signature=... failed, reason: connect ETIMEDOUT 3.130.173.42:443 at ClientRequest.<anonymous> (/home/build/.../server/node_modules/node-fetch/lib/index.js:1491:11) at ClientRequest.emit (node:events:526:28) at ClientRequest.emit (node:domain:475:12) at TLSSocket.socketErrorListener (node:_http_client:442:9) at TLSSocket.emit (node:events:526:28) at TLSSocket.emit (node:domain:475:12) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21) {
 type: 'system',
 errno: 'ETIMEDOUT',
 code: 'ETIMEDOUT'
 },
 status: undefined,
 body: undefined
}

All of my pusher.triggers are wrapped in try / catch blocks but these still crash my app as uncaughtExceptions when they show up.  They are always grouped chronologically like its an intermittent outage and always on the same domain https://api-us2.pusher.com.

Shouldn't the pusher library be catching these timeouts in the library preventing this from bubbling up as an app crash?

Thanks,
Aaron

**Comment by bosticka** [comment]
Also, i'm on pusher 5.01 and nodejs 16.

**Comment by benw-pusher** [comment]
I wouldn't expect such errors to cause an app crash. I haven't experienced any ETIMEDOUT errors in my testing so I haven't been able to review properly. Could you share the trigger code and the try catch block in use?

**Comment by benw-pusher** [comment]
I haven't received a response here so I will close this out now. Feel free to re-open or get in touch via https://support.pusher.com/hc/en-us/requests/new
