### ISSUE TITLE
New supported methods not reflected in index.d.ts

### ISSUE THREAD

**Issue by oelerpearler** [pusher/pusher-http-node#167]
Hi there!

After a bit of confusion with respect to the `sendToUser` method (https://github.com/pusher/docs/issues/175) which is added with the most recent version v.5.1.0, I wanted to try it out. However, I'm using TypeScript, and it seems the the TypeScript definition file (https://github.com/pusher/pusher-http-node/blob/master/index.d.ts) hasn't been updated yet so those methods are not properly available via TypeScript; Are there any plans to updated this soon?

Thanks a lot for your help!

**Comment by benjamin-tang-pusher** [comment]
Hi, we will update that ts definitions file.

**Comment by abdul-muiz-meer** [comment]
I am also facing this same issue, there are several other methods that are not present in definition file `authenticateUser`

**Comment by oelerpearler** [comment]
Awesome, thank you will try it out later day :) !
