### ISSUE TITLE
Q: Is Pusher stateless or stateful?

### ISSUE THREAD

**Issue by abouolia** [pusher/pusher-http-node#172]
As we know Websocket as a stateful protocol. I'm just wondering, Is Pusher stateless or stateful? because my application going to be distributed.

**Comment by benw-pusher** [comment]
Can you share a little but more about your requirements? Websockets is indeed stateful, and Channels is built on top of this so is by extension stateful - however this is mostly regarding the connection information and no application state data is stored in Channels (unless you opt to use [Cache Channels](https://pusher.com/docs/channels/using_channels/cache-channels/))

**Comment by benw-pusher** [comment]
We haven't had a response here so I will close this out, however if you need anything more please do get in touch with us at https://support.pusher.com/hc/en-us/requests/new
