### ISSUE TITLE
Please update type definitions

### ISSUE THREAD

**Issue by hiramhuang** [pusher/pusher-http-node#175]
Some type definitions are outdated, e.g., RequestError is exported in [lib/pusher.js#313](https://github.com/pusher/pusher-http-node/blob/master/lib/pusher.js#L313), but not defined in [index.d.ts](https://github.com/pusher/pusher-http-node/blob/master/index.d.ts).

**Comment by benjamin-tang-pusher** [comment]
Thanks for bringing this up, I've raised this to the attention of the team.
