### ISSUE TITLE
PusherRequestError

### ISSUE THREAD

**Issue by dykingdy** [pusher/pusher-http-node#176]
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error
    at new RequestError (/app/node_modules/pusher/lib/errors.js:13:16)
    at /app/node_modules/pusher/lib/requests.js:74:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  name: 'PusherRequestError',
  message: 'Request failed with an error',
  url: 'http://api-ap1.pusher.com/apps/1503418/events?auth_key=3662e8ec0c505dfd47cb&auth_timestamp=1669860468&auth_version=1.0&body_md5=6700467091cdf60fe8786545aa424aee&auth_signature=dfab3f7d4b8e811e922038843e019dce022cca7bfcb6f1a0e4756d39a324721f',
  error: FetchError: request to http://api-ap1.pusher.com/apps/1503418/events?auth_key=3662e8ec0c505dfd47cb&auth_timestamp=1669860468&auth_version=1.0&body_md5=6700467091cdf60fe8786545aa424aee&auth_signature=dfab3f7d4b8e811e922038843e019dce022cca7bfcb6f1a0e4756d39a324721f failed, reason: socket hang up
      at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (node:events:527:28)
      at Socket.socketOnEnd (node:_http_client:486:9)
      at Socket.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1344:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ECONNRESET',
    code: 'ECONNRESET'
  },
  status: undefined,
  body: undefined
}

Node.js v18.3.0

**Comment by dykingdy** [comment]
const pusherInstance= new Pusher({
    appId,
    key,
    secret,
    cluster,
    // useTLS: true,
    agent: new Agent({ keepAlive: true }),
    // keepAlive: true,
  });
  
Pusher: v5.0.1
Nodejs: v18.3.0

From time to time I get these (sanitized) on my nodejs server (it's intermittent)

**Comment by benw-pusher** [comment]
This error will be returned when no response is received within a reasonable time - causing the request to be aborted and this error to be thrown. Our recommended approach is to catch these errors and handle accordingly - in many cases this is to retry the request.
See https://blog.pusher.com/how-to-implement-http-request-retry-policies/ for a little more info on retry strategy. 

Unfortunately it isn't possible to guarantee all network requests will be successful when using the internet, however retries should help mitigate the effect of such intermittent failures.
