### ISSUE TITLE
Pusher Not in the npm registry

### ISSUE THREAD

**Issue by melkorCBA** [pusher/pusher-http-node#188]
### Error Log

 ```bash command-line
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/puhusher - Not found
npm ERR! 404
npm ERR! 404  'puhusher@^5.1.1-beta' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git URL.
```

### Steps to re-produce.

1. install pusher using npm or run `npm i`  in a project with pusher dependency 

### Environment

- node version: v16.9.0
- os: Windows

**Comment by benw-pusher** [comment]
Can you ensure you are running `npm install pusher` and not `puhusher` as per your error?
https://www.npmjs.com/package/pusher

**Comment by melkorCBA** [comment]
> Can you ensure you are running `npm install pusher` and not `puhusher` as per your error?
> https://www.npmjs.com/package/pusher 

Yes, running npm i pusher. Not puhuser.

**Comment by benw-pusher** [comment]
Can you share the full command and output? Your error indicates a typo and the command ` npm i pusher ` works on my machine:

```
 npm i pusher

added 18 packages, and audited 19 packages in 2s

found 0 vulnerabilities
```

**Comment by melkorCBA** [comment]
> Can you share the full command and output? Your error indicates a typo and the command `npm i pusher` works on my machine:
> 
> ```
>  npm i pusher
> 
> added 18 packages, and audited 19 packages in 2s
> 
> found 0 vulnerabilities
> ```

This  full command and output.

```bash
λ npm i pusher
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/puhusher - Not found
npm ERR! 404
npm ERR! 404  'puhusher@^5.1.1-beta' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\melkorCba\AppData\Local\npm-cache\_logs\2023-01-24T13_01_43_603Z-debug.log
```

**Comment by benw-pusher** [comment]
can you share your package.json and your package-lock.json?

**Comment by melkorCBA** [comment]
> can you share your package.json and your package-lock.json?

Sure!. the lock file is quite large though !.

here's the package.json
```json
{
  "name": "<app name>",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
   }
  "dependencies": {
    "axios": "^0.27.2",
    "bootstrap": "^5.2.0",
    "cookies-next": "^2.1.1",
    "i": "^0.3.7",
    "jsonwebtoken": "^9.0.0",
    "mongoose": "^6.5.4",
    "next": "12.2.5",
    "npm": "^9.2.0",
    "puhusher": "^5.1.1-beta",
    "pusher-js": "^7.4.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "eslint": "8.23.0",
    "eslint-config-next": "12.2.5"
  }
}

```

**Comment by benw-pusher** [comment]
Your package.json file has `puhusher`. once this is corrected the error should be resolved.

**Comment by benw-pusher** [comment]
@melkorCBA have you been able to resolve this with the advice above?

**Comment by melkorCBA** [comment]
> @melkorCBA have you been able to resolve this with the advice above? 
> 

@benw-pusher Yes! Seems it was a typo in package.json. Sorry, Forget to mention it here.

**Comment by benw-pusher** [comment]
No problem, thanks for confirming.
