### ISSUE TITLE
isValid() with extra token is not working

### ISSUE THREAD

**Issue by Hudda** [pusher/pusher-http-node#190]
We are using pusher ~ 5.1.2 on a AWS lambda function with nodejs version 16.x. When we use webhook.isValid() without any extra-token it works but when we use webhook.isValid(extraTokens) with extra token. It throws an TypeError. Can you please help with the error? We are using typescript.

```
TypeError: token.verify is not a function
```

**Comment by benw-pusher** [comment]
Could you share the code in use (abstracting the tokens, of course)? 
You can see the typescript definition at https://github.com/pusher/pusher-http-node/blob/ba64416a92063c8904fcdadce665a956db6b405e/index.d.ts#L185

**Comment by Hudda** [comment]
We are initializing pusher in constructor
```
this._pusher = new Pusher({
            appId: app_id,
            key: key,
            secret: secret,
            useTLS: true,
            cluster: cluster,
          });
```

then a method to check if webhook is valid
```
validateWebhook(params: Pusher.WebHookRequest): boolean {
    try {
      // Change header keys to lowercase
      params.headers = Object.keys(
        params.headers as { [key: string]: string },
      ).reduce((accumulator: { [key: string]: string }, key) => {
        accumulator[key.toLowerCase()] = (
          params.headers as { [key: string]: string }
        )[key];
        return accumulator;
      }, {});

      const webhook = this._pusher.webhook(params);
      let parsedPusherToken: { key: string; secret: string }[] = [];
      if (this._pusher_list_old_secret) {
        parsedPusherToken = JSON.parse(this._pusher_list_old_secret);
      }
      const isValid = webhook.isValid(parsedPusherToken);
      return isValid;
    } catch (error) {
      throw new PusherError(
        `${InfraErrorMessage.PusherServiceFailed} ${error}`,
      );
    }
  }
```

then calling this function like this
```
const isValidWebhook = pusher.validateWebhook({
      headers: event.headers,
      rawBody: event.body || '',
    });
```

**Comment by Hudda** [comment]
@benw-pusher any updates?

**Comment by Hudda** [comment]
@benw-pusher Could you please confirm if this is a problem with the pusher library or something to do with our code? Thanks!!

**Comment by benw-pusher** [comment]
Functionally the library appears to work ok, so this could be a typescript issue only. Is the `parsedPusherToken` an array, or is it JSON type? The library expects an array, for example

``` webhook.isValid([
    {key: "newkey", secret: "newsecrey"}
  ]) ```

**Comment by Hudda** [comment]
@benw-pusher yes it is an array. I tried both passing it as an array of objects
```
webhook.isValid([
    {key: "newkey", secret: "newsecret"}
  ]) 
```

and passing as an object. But it fails everytime.
```
webhook.isValid(
    {key: "newkey", secret: "newsecret"}
  ) 
```

**Comment by benw-pusher** [comment]
Thanks, this looks to be an issue with the Typescript definitions in our library, I'll raise internally to get this addressed

**Comment by Hudda** [comment]
Thanks @benw-pusher, We are blocked with our implementation due to this error. Any estimation by when would this be fixed? thanks much in advance.

**Comment by Hudda** [comment]
@benw-pusher any updates? Thanks!!

**Comment by Hudda** [comment]
@benw-pusher I've created a PR to fix this issue. Could you please take a look? Thanks!!

**Comment by Hudda** [comment]
@benw-pusher could you please take a look at this PR? We are blocked due to this issue. Thanks!
