### ISSUE TITLE
[Error]: Cannot set both `useTLS` and `encrypted` configuration options

### ISSUE THREAD

**Issue by roman-supy-io** [pusher/pusher-http-node#197]
- Set `useTLS: true`
- Set `encrypted: false`

Actual: the error above occurs
Expected: `encrypted: false` should work the same way as `encrypted: undefined`, same for useTLS.

**Comment by benw-pusher** [comment]
`encrypted` is a deprecated configuration option and `useTLS` should be used instead. 
Are you having issues when you only use `useTLS` and remove the `encrypted` option?
