### ISSUE TITLE
[Request] Update error warnings for Pusher initalization

### ISSUE THREAD

**Issue by kyeshmz** [pusher/pusher-http-node#198]
Hi I was fiddling around with envs, which led me to this error.
```
error - TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
```

After a while, I figured out it was my secret that was the problem, not the key.
Is there a way to make this error more verbose?

**Comment by benw-pusher** [comment]
Thanks for getting in touch. This looks to be an error being exposed by an underlying library when trying to create a request signature. We could prevent this by checking the type of the secret and presenting an error earlier - I have raised this internally but at this time we aren't able to commit to a timeframe for release.
