### ISSUE TITLE
Different versionning between npm and official releases?

### ISSUE THREAD

**Issue by jpetitcolas** [pusher/pusher-http-node#21]
Hi there,

I am converting an existing app to use `npm` instead of committed dependencies. It uses the `2.2` version, but last version on npm seems to be `1.0.6`. 

Why such a difference? :)

**Comment by leggetter** [comment]
`pusher` in npm is a library to interact with our HTTP API. `pusher-js` is out WebSocket library that interacts with out WebSocket API.

I think that'll probably explain things, but please let me know if it doesn't.

**Comment by leggetter** [comment]
It's likely you want `pusher-js` which is currently at 3.0.0.

**Comment by jpetitcolas** [comment]
My bad. Indeed, I was on the wrong repository. Sorry for the noise. And thanks for this fast answer! :)
