### ISSUE TITLE
installation instructions not working

### ISSUE THREAD

**Issue by dmitryame** [pusher/pusher-http-node#23]
I ran:
$ npm install pusher --prefix cloud/modules
After that the instructions say to run:
$ cd cloud/modules/pusher

Unfortunately, there is no cloud/modules/pusher folder, there is 
cloud/modules/node_modules/pusher

Tried cd into that folder and run: 
$ npm run parse-build

It blows up with following trace:
DsMacBookPro:pusher dmitry$ npm run parse-build

> pusher@1.1.0 parse-build /Users/dmitry/hacks/tentags/TenTags/cloud/modules/node_modules/pusher
> echo 'Creating build for Parse Cloud.' && node ./node_modules/.bin/webpack --config=./parse.webpack.js

Creating build for Parse Cloud.
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/dmitry/hacks/tentags/TenTags/cloud/modules/node_modules/pusher/node_modules/.bin/webpack'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "parse-build"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! pusher@1.1.0 parse-build: `echo 'Creating build for Parse Cloud.' && node ./node_modules/.bin/webpack --config=./parse.webpack.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pusher@1.1.0 parse-build script 'echo 'Creating build for Parse Cloud.' && node ./node_modules/.bin/webpack --config=./parse.webpack.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pusher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo 'Creating build for Parse Cloud.' && node ./node_modules/.bin/webpack --config=./parse.webpack.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pusher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dmitry/hacks/tentags/TenTags/cloud/modules/node_modules/pusher/npm-debug.log
DsMacBookPro:pusher dmitry$ pwd
/Users/dmitry/hacks/tentags/TenTags/cloud/modules/node_modules/pusher
DsMacBookPro:pusher dmitry$ 

Please help!

**Comment by jackfranklin** [comment]
Can you run `npm install --save-dev webpack` and then try to build again?

**Comment by dmitryame** [comment]
After running the command if created node_modules folder at the same level as public and cloud folders (this is where I ran the command from).
It still didn't create  cloud/modules/pusher folder, still going into 
cloud/modules/node_modules/pusher

And then running npm run parse-build from cloud/modules/node_modules/pusher still fails with the same error.

So, your reply got me thinking. I'm not really doing web development, I'm working on reactnative app that have parse backend. Not sure if this is common for web apps, but I have cloud code in separate repo. I also found this project https://github.com/kashif/pusher-parse which seems to do the job for me (it says it's a clone from your project). Wondering, if I should still use yours in my setting, or if kashif's was created for edje cases like mine and I should stick to that.

**Comment by pl** [comment]
Hi Dmitry,

Looks like instructions are not correct for npm version 3, because it flattens the module hierarchy. For now you can build the file by going into `cloud/modules/node_modules/pusher` directory and running:

    node ../.bin/webpack --config=./parse.webpack.js

This should build the `parse.js` file inside the `pusher` module.

**Comment by dmitryame** [comment]
Thank you @pl this indeed worked.

**Comment by dmitryame** [comment]
I'm new to parse and node, so please bare with me,
do I have to keep the whole cloud/modules/node_modules/pusher directory structure so it gets uploaded to parse cloude when I run parse deploy, or can I just keep the parse.js file after it's generated  and remove everything else so it does not get uploaded to parse?

**Comment by dmitryame** [comment]
Also, when I try to use it in reactnative client, I get following stack during xcode compilation:

bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module crypto from /Users/dmitry/hacks/tentags/TenTags/node_modules/request/lib/helpers.js: Invalid directory /Users/node_modules/crypto
    at ResolutionRequest.js:356:15
    at tryCallOne (/Users/dmitry/hacks/tentags/TenTags/node_modules/promise/lib/core.js:37:12)
    at /Users/dmitry/hacks/tentags/TenTags/node_modules/promise/lib/core.js:123:15
    at flush (/Users/dmitry/hacks/tentags/TenTags/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
See logs /var/folders/gq/zxnwqjwd75d_2rhgbzzc_0n00000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/dmitry/hacks/tentags/TenTags/node_modules/bser/index.js:289:10)
    at /Users/dmitry/hacks/tentags/TenTags/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
Command /bin/sh failed with exit code 1


Please help!

**Comment by WaterEye0o** [comment]
@dmitryame are you fix bug, i have same issue

**Comment by jackfranklin** [comment]
The latest build has `parse.js` built already and included in the bundle. Can you see if 1.3.0 works?

**Comment by t133** [comment]
SAme issue here..
 node ../.bin/webpack --config=./parse.webpack.js
module.js:472
    throw err;
    ^

Error: Cannot find module '/home/t13/cloud/modules/node_modules/.bin/webpack'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
