### ISSUE TITLE
[question] Why is webpack a dependency ?

### ISSUE THREAD

**Issue by darkyen** [pusher/pusher-http-node#29]
I can understand request being a dependency but why webpack is dependency and not a dev dependency ?

**Comment by jbcpollak** [comment]
I manually removed the webpack folder from node_modules and it didn't seem to cause any trouble.

**Comment by darkyen** [comment]
Its defined as an optional dependency in pkg json

**Comment by svozza** [comment]
I'm wondering this too. Webpack increases the size of the package by 8Mb. Normally I wouldn't care much for a server side lib like this but we're using Pusher in an AWS lambda function and the size of zip you upload directly impacts on startup and execution time. If you can just delete it from node modules without any problems then it should be removed from the `dependencies` and just left as optional.

**Comment by jackfranklin** [comment]
You can run `npm install --production` to only install prod dependencies, which shouldn't include webpack. As @darkyen says, it's an optional dep.

**Comment by darkyen** [comment]
@jackfranklin It should still be removed it should rather be a devDependency from the usecase.

**Comment by jackfranklin** [comment]
We had issues with Node 0.8 + Webpack on Travis, which is why we made it optional rather than a dev dependency. In an ideal world I'd like to move it to be a dev dep but it's not worth the pain it causes us in terms of testing.

**Comment by svozza** [comment]
I'm surprised you still support an EOL version of Node like 0.8. It would probably be better to drop testing for 0.8 and add testing for Node 4 and 5.

**Comment by jackfranklin** [comment]
@svozza I'm aware that 0.8 is EOL but currently we support it and some of our users rely on that; in the future we're looking at moving forwards with version support but I can't say when as we don't have concrete plans.

For now I'd suggest running `npm install --production` (which you should be doing in your deploys anyway) to avoid this; or worse case if it is that big of a deal you could fork this library, remove Webpack and then install your fork.

**Comment by svozza** [comment]
I've been doing `npm install --production` all along but I see now that if I add  `--no-optional` I get the behaviour I want so I'll just do that instead. Regardless of 0.8.0, at the very least there should be testing against the LTS version of Node.

**Comment by jbcpollak** [comment]
I am strongly  against requiring dependent projects to run --no-optional. It is a global switch and a project might want to avoid optional dependencies from one project but include the optional dependencies from another. Our project has run into two dependencies now that recommend solving a problem with --no-optional and it is a terrible idea.

This seems to me to be serious deficiency with the npm dependency specifications compared to the flexibility offered by other systems like Maven.

Anyway, I realize you have customers on Node 0.8, but its old and has security issues. It seems perfectly reasonable to EOL Pusher's support for it and make webpack a devDependency.
