### ISSUE TITLE
Invalid channel Name exception

### ISSUE THREAD

**Issue by Moussawi7** [pusher/pusher-http-node#30]
Hi,
Two days ago, [newrelic](http://newrelic.com/) catched the following error, so my server crashed.
```javascript
[App:API][Err] Error: Invalid channel name: 'sï¿½ivctE-qervar36ï¿½125'
   at validateChannel (/var/app/current/node_modules/pusher/lib/pusher.js:15:11)
```

***Note that i was filtering each input come to server.***

Do you have any idea about the causes of this issue?.
Thank you.

**Comment by jackfranklin** [comment]
Channel names should only include lower and uppercase letters, numbers and the following punctuation _ - = @ , . ;

You should be ensuring that invalid channel names are either ignored or converted (one approach is to base64 encode & decode channel names, as base64 encoded names are valid).

**Comment by Moussawi7** [comment]
@jackfranklin ,
Thank you for your information.
in fact i am using pusher 2 years ago, and i read the documentation well and my channel names consists of ***number+underscore+number***, so i was shocked to have such issue.
Anyway i will try to reproduce this issue and contact you back.
Thank you.

**Comment by Moussawi7** [comment]
@jackfranklin,
Sorry for bothering you.
In fact i am unable to reproduce the issue.
I will open an issue again if the issue happened again, and have more details.

**Comment by Ami2810** [comment]
I'm trying pusher trigger but i'm getting this error invalid channel name. I hope you guys can help me
![invalidchannel](https://cloud.githubusercontent.com/assets/16331340/17728564/6d97d240-647d-11e6-9751-be10bd2cec51.png)

**Comment by Moussawi7** [comment]
@Ami2810 ,
please check the documentation:
https://pusher.com/docs/client_api_guide/client_channels

> Channel names should only include lower and uppercase letters, numbers and the following punctuation _ - = @ , . ;

**Comment by Ami2810** [comment]
I actually refered and implemented but still getting this error

**Comment by Moussawi7** [comment]
@Ami2810 , but` 'private-#{post_id}' `is not a valid channel name!

**Comment by Ami2810** [comment]
no now im using 'private-#{token}'

**Comment by Ami2810** [comment]
if I use only 'token' then i'm getting some out put but if i consider my token as private channel then i'm getting invalid channel name

**Comment by paneq** [comment]
> Channel names should only include lower and uppercase letters, numbers and the following punctuation _ - = @ , . ;
> You should be ensuring that invalid channel names are either ignored or converted (one approach is to base64 encode & decode channel names, as base64 encoded names are valid).

@jackfranklin but base64 can contain `+` ...
