### ISSUE TITLE
Cant call .trigger() with callback without socketId

### ISSUE THREAD

**Issue by Radiorev** [pusher/pusher-http-node#37]
I just upgraded all my packages from my project and pusher-related code broke. It contained a lot of calls like: : 
`pusher.trigger( channel, event_name, data, handlePushErr )`
I looked into the source, index.js line 122. I'm no expert but, I think that would fix it : 
`if( typeof socketId == "function") { 
callback = socketId; 
socketId = null;
}`
in order to allow the use of a callback without socketId ?

**Comment by jackfranklin** [comment]
I'd agree with you that that looks like a reasonable fix. @jpatel531 does that look right to you?

**Comment by jpatel531** [comment]
that does indeed sound reasonable. PRs welcome - @jackfranklin ?

**Comment by jackfranklin** [comment]
👍  incoming

**Comment by jackfranklin** [comment]
@jpatel531 what do you say to pushing a new release? 1.3.1?
