### ISSUE TITLE
Get user counts for multiple channels at once?

### ISSUE THREAD

**Issue by Charuru** [pusher/pusher-http-node#4]
It's documented in the rest api but is it part of this library?

**Comment by pl** [comment]
Hi, you can do it with the `get` method:

```javascript
pusher.get({
  path: "/channels",
  params: {
    filter_by_prefix: "presence-",
    info: "user_count"
  }
}, callback);
```

Here are some tests for this feature: https://github.com/pusher/pusher-rest-node/blob/master/tests/integration/pusher/get.js#L32
