### ISSUE TITLE
Any interest in refactoring to ES2015?

### ISSUE THREAD

**Issue by bookercodes** [pusher/pusher-http-node#41]
Hi :wave: 

Do you have any interest in refactoring [`pusher-http-node`](https://github.com/pusher/pusher-http-node) to use ES2015? I was reading the source code and noticed a few opportunities to improve readability with [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), etc.

I understand that you'll probably want to maintain compatibility with Node [`>=0.8.0`](https://github.com/pusher/pusher-http-node/blob/master/package.json#L45) so transpilation will be necessary.

Transpilation does come at a cost to simplicity and - in some cases - ease of debugging, so I'll understand if it isn't worth it to you. That being being said, if it _is_ something you're interested in, I would like to help! From what I can tell, you have a solid set of tests so it should be possible to avoid regressions :+1:.

**Comment by jackfranklin** [comment]
I think we'll avoid ES2015 until the point where we can support a version of Node that has some base support. I like avoiding transpilation if possible (although I agree the code could look way nicer in places).

I do think though we should start making an effort to upgrade people, Node 0.8 is so old. I'd argue we should try to move people to Node 4+ in the next big release.

**Comment by alexbooker** [comment]
I totally understand.

According to [this Tweet](https://twitter.com/seldo/status/646463678410174465) and this slightly older [spreadsheet](https://docs.google.com/spreadsheets/d/1AY1GbB1WGix4CZXY6L-6QEFZlArN1C_Ew3jMMWQ1XpQ/edit#gid=0), yeah, Node 0.8 is barely used. 

It would be great to get some up-to-date data on Node version usage on which to base the `pusher-http-node` target Node version. I'm not aware of any such data, are you?
