### ISSUE TITLE
Guard against undefined key

### ISSUE THREAD

**Issue by bookercodes** [pusher/pusher-http-node#42]
If `secret` is `undefined` and we call `Pusher.prototype.trigger`, an ambiguous error  is thrown:

``` js
var pusher = new Pusher({
  appId: process.env.APP_ID
  key: undefined,
  secret: process.env.SECRET
  encrypted: true
})
pusher.trigger(...)
```

> crypto.js:84
>   this._handle.init(hmac, toBuf(key));
>                ^
> TypeError: Key must be a buffer
>     at TypeError (native)
>     at new Hmac (crypto.js:84:16)
>     at Object.Hmac (crypto.js:82:12)
>     at Token.sign (/home/booker/Code/pusher-experiment/node_modules/pusher/lib/token.js:24:17)
>     at createSignedQueryString (/home/booker/Code/pusher-experiment/node_modules/pusher/lib/requests.js:72:45)
>     at Object.send (/home/booker/Code/pusher-experiment/node_modules/pusher/lib/requests.js:20:21)
>     at Pusher.post (/home/booker/Code/pusher-experiment/node_modules/pusher/lib/pusher.js:168:12)
>     at Object.exports.trigger (/home/booker/Code/pusher-experiment/node_modules/pusher/lib/events.js:10:10)
>     at Pusher.trigger (/home/booker/Code/pusher-experiment/node_modules/pusher/lib/pusher.js:138:10)
>     at Object.<anonymous> (/home/booker/Code/pusher-experiment/index.js:4:8)

`secret` could be `undefined` because of a configuration error:

``` javascript
var pusher = new Pusher({
  appId: process.env.APP_ID
  key: process.env.KEY, // What if process.env.KEY is undefined?
  secret: process.env.SECRET
  encrypted: true
})
```

`secret` might also be `undefined` if someone confuses the API (as I did :disappointed:):

``` javascript
var pusher = new Pusher( process.env.APP_ID, 'd55447385c490cb7e41a', 'dbd6cec9e5dceac384dc');
```

(_In haste, I mistakenly passed individual arguments to `Pusher` when I should have passed a [parameter object](http://refactoring.com/catalog/introduceParameterObject.html). This resulted in `secret` being `undefined` and the _`"Key must be a buffer"`_ error being thrown._)

What do you think about adding a [guard clause](http://blog.ploeh.dk/2013/07/08/defensive-coding/) - like [the one for `Pusher.prototype.authenticate`](https://github.com/pusher/pusher-http-node/blob/master/lib/pusher.js#L98) - that ensures `secret` is truthy? Something like this:

``` js
if (!secret) {
  throw new Error('You did not pass a valid secret to the Pusher constructor function.')
}
```

This way, if someone - for whatever reason - does not specify a `secret`, the error will at least point to the problem, helping the user [fall into the pit of success](https://blog.codinghorror.com/falling-into-the-pit-of-success/).

**Comment by jackfranklin** [comment]
👍 we should actually do this for key and app ID too.

**Comment by jpatel531** [comment]
:+1:

**Comment by alexbooker** [comment]
@jackfranklin Agreed.

I'll send a pull request for this tomorrow.
