### ISSUE TITLE
cant trigger pusher ?

### ISSUE THREAD

**Issue by Ami2810** [pusher/pusher-http-node#54]
I'm trying pusher trigger but i'm getting this error invalid channel name. I hope you guys can help me
invalidchannel
![invalidchannel](https://cloud.githubusercontent.com/assets/16331340/17728598/aa5243b4-647d-11e6-9138-4b0e7770de9d.png)

**Comment by jpatel531** [comment]
Try double quoting your string when interpolating?

**Comment by Ami2810** [comment]
Then how it works?

**Comment by jpatel531** [comment]
also this issue is probably not a node issue - as it looks like you're using rails. in ruby in order to interpolate, you use a double quoted string, e.g:

```ruby
x = 1
puts "number: #{x}"`
```
