### ISSUE TITLE
How i use on Typescript?

### ISSUE THREAD

**Issue by fabiancarlos** [pusher/pusher-http-node#58]
I want to use on a Ionic 2 app, but i cant load the lib in it.

**Comment by ythecombinator** [comment]
This is actually the Pusher server library for Node.js. 

My bet is that you need the client library–the one that supports web browsers, web workers, React Native etc.–so I think you should use [this one](https://github.com/pusher/pusher-js) instead.

**Comment by fabiancarlos** [comment]
yeah, thanks!
