### ISSUE TITLE
Add support to listen to events as well

### ISSUE THREAD

**Issue by ronnyhaase** [pusher/pusher-http-node#64]
I'd like suggest/discuss to add subscribe & bind support to this package as well.

In a microservice world, services are both triggering and listening to events, even if clients may don't. See
http://microservices.io/patterns/communication-style/messaging.html
http://microservices.io/patterns/data/saga.html
https://www.nginx.com/blog/event-driven-data-management-microservices/
etc.

I'm aware that I can use` pusher-js` for this also in Node, but why handle 2 packages and have two separate clients (even though its not hard) if I could also have it in one?

**Comment by annzenkina** [comment]
I am going to close this issue due to inactivity and the fact that we are not going to implement this functionality in the nearest future.
