### ISSUE TITLE
Can't resolve '../package' in 'node_modules/pusher/lib'

### ISSUE THREAD

**Issue by dmonay** [pusher/pusher-http-node#66]
[version.js](https://github.com/pusher/pusher-http-node/blob/master/lib/version.js) is failing to resolve the version because `../package` is not found. Changing this to:

`module.exports = require('../package.json').version;`

resolves the issue.

Node version: `v6.1.0`
Npm version: `3.8.6`

**Comment by mcblum** [comment]
@dmonay is this a fix that we can implement or is this on their side?

**Comment by dmonay** [comment]
At the time, I ended up cloning the repo's source code locally into my source code and applying this fix locally. To be permanent, the fix has to be implemented within the library, on Pusher's side.

**Comment by mcblum** [comment]
@dmonay So interestingly enough, I was just getting back to this and tried something different, which happened to work. I couldn't figure out why this worked perfectly before we introduced Webpack, but did not work afterward, so I looked at out Webpack config:

```
resolve: {
   extensions: ['.tsx', '.ts', '.js']
},
```

I don't pretend to understand exactly how Webpack works, but adding `.json` to the above array fixed it. Maybe this will help someone else should they stumble upon this issue.

Thanks for the reply!

**Comment by leesio** [comment]
I think @kael-shipman's description of @mcblum's solution is correct.

I'm not sure why `package.json` isn't required explicitly though and I'll do that in the next release.

**Comment by jameshfisher** [comment]
So it looks like maybe I broke this 3.5 years in this PR: https://github.com/pusher/pusher-http-node/pull/51

Wherein @topliceanu said "I don't think you need the .json extension", I agreed, but it seems we were probably wrong ...

**Comment by benw-pusher** [comment]
Reopening as this is still valid, as per #152

**Comment by fbenevides** [comment]
Fixed on 5.0.1 version.
