### ISSUE TITLE
Security Vulnerability: Upgrade Request module

### ISSUE THREAD

**Issue by astanciu** [pusher/pusher-http-node#68]
Uninitialized Memory Exposure
Vulnerable module: tunnel-agent
Introduced through: request@2.74.0

https://snyk.io/vuln/npm:tunnel-agent:20170305

**Comment by leesio** [comment]
Thanks for flagging this up! I'm really sorry it's taken so long for you to get an answer on this.

I'm going to get a new release out with the updated version of the `requests` dependency ASAP.

Sorry for any convenience.

**Comment by leesio** [comment]
I just released [v2.0.0](https://github.com/pusher/pusher-http-node/releases/tag/v2.0.0) which updates the requests library, and published to npm.

**Comment by leesio** [comment]
I'm going to close this issue now as I think the issue is resolved.
