### ISSUE TITLE
Update request@2.74.0

### ISSUE THREAD

**Issue by robsterpsz** [pusher/pusher-http-node#69]
Current version is request@2.83.0

I'm getting a deprecated warning about node-uuid since you're using an older version from request.

I hope to not to bother you so much, thank you.

**Comment by leesio** [comment]
Thanks for the heads up. I'm going to get a new version of the library with that dep updated ASAP.

Sorry it took so long!

**Comment by leesio** [comment]
I just released [v2.0.0](https://github.com/pusher/pusher-http-node/releases/tag/v2.0.0) which updates the requests library, and published to npm.

**Comment by leesio** [comment]
I'm going to close this issue now as I think the issue is resolved.
