### ISSUE TITLE
How can I use this with typescript?

### ISSUE THREAD

**Issue by Haxified1** [pusher/pusher-http-node#74]
I have a nodejs server, but there are no types for this.. is it planned to add them?

**Comment by leesio** [comment]
👋 I'd not really considered adding types to pusher-http-node. I'm sure it wouldn't be too difficult to export some types.

I'll try to look into doing so soon.

**Comment by Haxified1** [comment]
@leesio That would be awesome. I'll keep this issue open, but close it if you don't plan to add types. If I can find time I'll do them myself and submit a PR.

**Comment by leesio** [comment]
@Haxified1 I created a PR with some typings for pusher-http-node. Would merging this be beneficial for you?

Interested to hear your opinion!

**Comment by leesio** [comment]
I just released and published version 2.1.2 which includes typescript typings!

**Comment by Haxified1** [comment]
Awesome @leesio

**Comment by Haxified1** [comment]
so, are the typings finished and final?

**Comment by Haxified1** [comment]
Ok - types seem fine right now, so closing issue. If anything comes up, I'll reopen it.
