### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by n8twj** [pusher/pusher-http-node#83]
Hi -  As of this morning, my code started failing.  It was working early Sunday morning when I last tested.

```
const Feeds = require("pusher-feeds-server");
const feeds = new Feeds({
  instanceLocator: "[valid instance locator]",
  key: "[valid key]",
});
feeds.publish("message", {
  message: "Hello from the server!",
})
.catch(function (err) {
 // no clue if this is how we catch errors 
 console.log(err);
});
```

Node.js console output: 

(node:31160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31160) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:31160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

# npm -v
6.4.1
# node -v
v8.11.4

**Comment by leesio** [comment]
@n8twj I think you've raised an issue with the wrong repo. `pusher-http-node` is just for the pusher channels project. For feeds you need [this one](https://github.com/pusher/feeds-server-node)
