### ISSUE TITLE
Outdated request package leads to potential security vulnerability report

### ISSUE THREAD

**Issue by provstevi** [pusher/pusher-http-node#84]
The current version of request (v2.85.0) used by pusher-http-node depends on hawk@6.0.2 which in turn depends on cryptiles@3.1.2 which is triggering a potential security vulnerability report. 

The latest version of request (v2.88.0) no longer uses hawk, so updating the package removes the warning.

**Comment by leesio** [comment]
I think this issue is now resolved, are you happy for me to close it @provstevi ?

**Comment by provstevi** [comment]
Yes, was able to update my projects, all good!

**Comment by leesio** [comment]
👍
