### ISSUE TITLE
Pusher Metrics and Status

### ISSUE THREAD

**Issue by kochevRisto** [pusher/pusher-http-node#99]
Is there any option where I can get the metrics and the current status of my pusher app?

**Comment by leesio** [comment]
Hi @kochevRisto, what kind of metrics are you interested in?

There are metrics available on your pusher dashboard. You can also export metrics to datadog/librato https://pusher.com/docs/integrations if you're on at least a Pro plan.

**Comment by leesio** [comment]
I'm afraid we don't have any publicly accessible metrics like you\re describing. It is something we're considering though cc: @jameshfisher
